input {
  gelf {
    port => 12201
  }
  tcp {
    port => 24224
    codec => json_lines
  }
}

filter {
  if [kubernetes] and [kubernetes][container_name] {
    mutate {
      add_field => {
        "app" => "%{[kubernetes][container_name]}"
        "log_source" => "kubernetes"
      }
    }
  } else {
    mutate {
      add_field => {
        "app" => "%{container_name}"
        "log_source" => "docker-compose"
      }
    }
  }

  mutate {
    remove_field => ["stream"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "medical-chatbot-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
